version: 2
updates:
- package-ecosystem: github-actions
  directory: "/.github/workflows"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Madrid
  open-pull-requests-limit: 10
  commit-message:
    prefix: "[Dep][github] "
  labels:
    - dependabot
  reviewers:
    - "aplazame/squad_core-backend-reviewers"
